services:
  - type: web
    name: devendra-photography-api
    env: python
    region: oregon
    plan: starter
    runtime: python
    pythonVersion: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: dsp_photography
      - key: FRONTEND_URL
        value: https://devendra-photography-site.vercel.app